"""Build the participant starter kit into ``public/starter-kit.zip``.

    python build_kit.py

Run this after changing anything under ``starter-kit/`` or ``src/auction/`` and
commit the resulting zip — the VM serves files straight out of the repo and has
no build step, so the archive has to be in git.

``starter-kit/auction_reference/`` is regenerated here rather than kept by hand,
so the copy participants read can never drift from the engine that scores them.
"""

from __future__ import annotations

import shutil
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
KIT_DIR = REPO_ROOT / "starter-kit"
REFERENCE_DIR = KIT_DIR / "auction_reference"
ENGINE_DIR = REPO_ROOT / "src" / "auction"
OUTPUT = REPO_ROOT / "public" / "starter-kit.zip"

HEADER = '''"""READ-ONLY COPY — generated by build_kit.py, do not edit.

This is the engine that actually runs the auction, included so you can see
exactly how a round is simulated. Editing it changes nothing about how your
submission is scored.
"""

'''


def refresh_reference() -> list[Path]:
    """Regenerate `starter-kit/auction_reference/` from `src/auction/`."""
    if REFERENCE_DIR.exists():
        shutil.rmtree(REFERENCE_DIR)
    REFERENCE_DIR.mkdir(parents=True)

    copied = []
    for source in sorted(ENGINE_DIR.glob("*.py")):
        target = REFERENCE_DIR / source.name
        target.write_text(HEADER + source.read_text(encoding="utf-8"), encoding="utf-8")
        copied.append(target)
    return copied


def kit_files() -> list[Path]:
    files = [
        KIT_DIR / "Template.py",
        KIT_DIR / "README.md",
        REPO_ROOT / "run_local.py",
    ]
    files += sorted((KIT_DIR / "sample_bots").glob("*.py"))
    files += sorted(REFERENCE_DIR.glob("*.py"))
    return [f for f in files if f.is_file()]


def build() -> Path:
    refresh_reference()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    # `run_local.py` imports `src.auction...`, so the kit ships that layout too.
    with zipfile.ZipFile(OUTPUT, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in kit_files():
            relative = path.relative_to(REPO_ROOT)
            if relative.parts[0] == "starter-kit":
                arcname = Path("starter-kit", *relative.parts[1:])
            else:
                arcname = relative
            archive.write(path, f"trading-bot-starter-kit/{arcname.as_posix()}")

        for source in sorted(ENGINE_DIR.glob("*.py")):
            archive.write(
                source,
                f"trading-bot-starter-kit/src/auction/{source.name}",
            )
        archive.writestr("trading-bot-starter-kit/src/__init__.py", "")

    return OUTPUT


if __name__ == "__main__":
    output = build()
    size_kb = output.stat().st_size / 1024
    with zipfile.ZipFile(output) as archive:
        count = len(archive.namelist())
    print(f"  built {output.relative_to(REPO_ROOT)} — {count} files, {size_kb:.1f} KB")
