"""READ-ONLY COPY — generated by build_kit.py, do not edit.

This is the engine that actually runs the auction, included so you can see
exactly how a round is simulated. Editing it changes nothing about how your
submission is scored.
"""

"""Auction engine for the Quant Guild Trading Bot competition.

Public entry points are added as the modules are implemented (see
docs/BUILD_CHECKLIST.md, phase 0.C / 1.B).
"""
